spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    contexts: dev
    change-log: classpath:db/db.changelog-master.yml
server:
  port: 8080

